env:
  global:
    - ANDROID_SDK_VERSION=22.0.1
    - ANDROID_SDK_TGZ=android-sdk_r${ANDROID_SDK_VERSION}-linux.tgz
    - ANDROID_API_LEVEL=17
    - ANDROID_HOME=`pwd`/android-sdk-linux
    - TARGET=release-nomarket
language: java
before_install:
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - set
  # download the latest android sdk and unzip (http://developer.android.com/sdk/index.html)
  - wget http://dl.google.com/android/${ANDROID_SDK_TGZ}
  - tar -zvxf ${ANDROID_SDK_TGZ}
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  # or see http://developer.android.com/guide/topics/manifest/uses-sdk-element.html
  - android update sdk --filter 1,2,${ANDROID_API_LEVEL} --no-ui --force <<< y
script:
  - android update project --path astrid/ --target ${TARGET}
  - ant ${TARGET}
