language: java
before_install:
  # download the latest android sdk and unzip (http://developer.android.com/sdk/index.html)
  - export ANDROID_SDK_TGZ=android-sdk_r22.0.1-linux.tgz
  - wget http://dl.google.com/android/${ANDROID_SDK_TGZ}
  - tar -zxf ${ANDROID_SDK_TGZ}
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  # or see http://developer.android.com/guide/topics/manifest/uses-sdk-element.html
  - android update sdk --filter 1,2,17 --no-ui --force <<< y
script:
  - ant release
